version: 2
updates:

  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "yearly"
    groups:
      kotlin:
        patterns:
          - "org.jetbrains.kotlin.*"
          - "com.google.devtools.ksp"
          - "kotlin*"
          - "*kotlin*"
      spring:
        patterns:
          - "*spring*"
      junit:
        patterns:
          - "junit*"
          - "*junit*"
      slf4j:
         patterns:
           - "*slf4j*"
           - "slf4j*"
           - "*slf4j"
      arrow:
          patterns:
            - "arrow"
            - "*arrow"
            - "arrow*"
            - "arrow*"

  - package-ecosystem: "gradle"
    directory: "/experiments/dokka-multilevel"
    schedule:
      interval: "yearly"
    groups:
      kotlin:
        patterns:
          - "org.jetbrains.kotlin.*"
          - "com.google.devtools.ksp"
          - "kotlin*"
          - "*kotlin*"
      spring:
        patterns:
          - "*spring*"
      junit-jupiter:
        patterns:
          - "junit*"
          - "*junit*"
      slf4j:
         patterns:
           - "*slf4j*"
           - "slf4j*"
           - "*slf4j"
      arrow:
          patterns:
            - "arrow"
            - "*arrow"
            - "arrow*"
            - "*arrow*"

  - package-ecosystem: "maven"
    directory: "/demo-projects/fibonacci"
    schedule:
      interval: "yearly"
    groups:
      postgresql:
        patterns:
          - "*postgresql*"
      maven:
        patterns:
          - "*maven*"
      kotlin:
        patterns:
          - "*kotlin*"
      spring:
        patterns:
          - "*spring*"
      arrow:
        patterns:
          - "arrow"
          - "*arrow"
          - "arrow*"
          - "*arrow*"
